FROM node:24-alpine3.21

WORKDIR /app


COPY package*.json tsconfig.json ./
RUN npm install

COPY src ./src
RUN npm run build

WORKDIR /app

# Copy only built JS + node_modules + package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package*.json ./

EXPOSE 3000

CMD ["node", "dist/server.js"]
